#!/usr/bin/env python3
"""
act demo: single-episode rollout driven by a WebSocket policy server.

Purpose
-------
Connects to a server speaking the `policy_websocket` protocol (default
companion: `tests/test_random_policy_server.py`), runs ONE episode of the
selected act bimanual sim task with per-step logging, then exits. No success
aggregation, no dataset, no checkpoint — this is the "show me one run"
sibling of run_eval.py. Use it to sanity-check a new policy server or to
watch a single rollout interactively (with --gui under the X11 compose
profile).

Each invocation creates `<log_dir>/demo/<task>--<YYYYMMDD_HHMMSS>/` so that
downstream video / log dumps land in a per-run directory rather than
overwriting earlier runs. A light `demo.log` mirrors stdout — enough to grep
after the fact without reaching for a full eval pipeline.

Action layout (14-D, absolute joint positions + normalized gripper):
    [ left_arm_qpos(6), left_gripper(1),
      right_arm_qpos(6), right_gripper(1) ]

Example
-------
    # Terminal A — start the companion random-policy server (action_dim=14)
    python tests/test_random_policy_server.py --port 8000

    # Terminal B — run a single episode against it
    python scripts/run_demo.py --policy_server_addr localhost:8000 \\
        --task_name sim_transfer_cube_scripted --n-steps 50

    # Inspect the per-run directory afterwards
    ls logs/demo/sim_transfer_cube_scripted--*/

Generated by benchmark-env-generator (IL Category).
"""

import argparse
import atexit
import os
import signal
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from constants import SIM_TASK_CONFIGS
from policy_websocket import WebsocketClientPolicy
from sim_env import BOX_POSE, make_sim_env
from utils import sample_box_pose, sample_insertion_pose, set_seed


ACTION_DIM = 14


def log(msg: str, log_file: Optional["os.PathLike"] = None) -> None:
    """Print to stdout and, if open, also write to a log file (flushed each call)."""
    print(msg)
    if log_file is not None and not log_file.closed:
        log_file.write(msg + "\n")
        log_file.flush()


def set_initial_pose(task_name: str) -> None:
    if "sim_transfer_cube" in task_name:
        BOX_POSE[0] = sample_box_pose()
    elif "sim_insertion" in task_name:
        BOX_POSE[0] = np.concatenate(sample_insertion_pose())


def extract_top_frame(obs) -> Optional[np.ndarray]:
    """Return the 'top' camera RGB frame (H, W, 3) uint8, or None if unavailable."""
    if "images" not in obs:
        return None
    images = obs["images"]
    if "top" in images:
        return np.asarray(images["top"], dtype=np.uint8)
    if images:
        first = next(iter(images.values()))
        return np.asarray(first, dtype=np.uint8)
    return None


def build_observation(ts, task_name: str) -> dict:
    obs = ts.observation
    return {
        "qpos": np.asarray(obs["qpos"], dtype=np.float32),
        "qvel": np.asarray(obs.get("qvel", []), dtype=np.float32),
        "images": {n: np.asarray(img) for n, img in obs.get("images", {}).items()},
        "task_description": task_name,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Single-episode demo against a policy server on an act bimanual task.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--policy_server_addr", required=True,
                        help="host:port of the WebSocket policy server")
    parser.add_argument("--task_name", type=str, default="sim_transfer_cube_scripted",
                        choices=list(SIM_TASK_CONFIGS.keys()),
                        help="Which act task to roll out")
    parser.add_argument("--n-steps", dest="n_steps", type=int, default=None,
                        help="Max steps for the single episode "
                             "(default: task_cfg['episode_len'])")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--policy", type=str, default="randomPolicy",
                        help="Policy name for the log header (free-form)")
    parser.add_argument("--gui", action="store_true",
                        help="Call env._physics.render() each step (X11 compose only)")
    parser.add_argument("--log_dir", type=str, default="./logs",
                        help="Parent dir for per-run demo outputs (created if missing)")
    parser.add_argument("--save_video", action="store_true",
                        help="Record the 'top' camera stream and write demo.mp4 to run_dir.")
    parser.add_argument("--video_fps", type=int, default=30)
    args = parser.parse_args()

    set_seed(args.seed)
    task_cfg = SIM_TASK_CONFIGS[args.task_name]
    if args.n_steps is None:
        args.n_steps = task_cfg["episode_len"]

    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(args.log_dir, "demo", f"{args.task_name}--{date_str}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, "demo.log")
    log_file = open(log_path, "w")

    def _cleanup(signum=None, frame=None):
        try:
            if not log_file.closed:
                log_file.close()
        finally:
            sys.stdout.flush()
            sys.stderr.flush()
        if signum is not None:
            os._exit(1)

    signal.signal(signal.SIGINT, _cleanup)
    signal.signal(signal.SIGTERM, _cleanup)
    atexit.register(lambda: None if log_file.closed else log_file.close())

    log("=" * 60, log_file)
    log("act demo", log_file)
    log("=" * 60, log_file)
    for k, v in sorted(vars(args).items()):
        log(f"  {k}: {v}", log_file)
    log(f"  run_dir: {run_dir}", log_file)
    log("=" * 60, log_file)
    log("", log_file)

    host, port = args.policy_server_addr.rsplit(":", 1)
    client = WebsocketClientPolicy(host=host, port=int(port))
    meta = client.get_server_metadata()
    log(f"server metadata: {meta}", log_file)
    server_dim = meta.get("action_dim") if isinstance(meta, dict) else None
    if server_dim is not None and int(server_dim) != ACTION_DIM:
        raise ValueError(
            f"task_name={args.task_name} expects action_dim={ACTION_DIM}, "
            f"but server returned {server_dim}."
        )

    set_initial_pose(args.task_name)
    env = make_sim_env(args.task_name)
    env_max_reward = env.task.max_reward
    log(f"env_max_reward = {env_max_reward}", log_file)

    ts = env.reset()
    client.reset()

    if args.gui:
        try:
            import matplotlib.pyplot as plt
            ax = plt.subplot()
            plt_img = ax.imshow(env._physics.render(height=480, width=640, camera_id="angle"))
            plt.ion()
        except Exception as e:
            log(f"[warn] gui setup failed ({e}); falling back to headless", log_file)
            args.gui = False

    frames = []
    highest_reward = 0.0
    last_step = 0
    try:
        for step in range(args.n_steps):
            last_step = step
            if args.gui:
                plt_img.set_data(env._physics.render(height=480, width=640, camera_id="angle"))
                plt.pause(0.001)

            observation = build_observation(ts, args.task_name)
            if args.save_video:
                frame = extract_top_frame(ts.observation)
                if frame is not None:
                    frames.append(frame)

            response = client.infer(observation)
            action = np.asarray(response["actions"], dtype=np.float32)
            if action.ndim > 1:
                action = action[0]
            if action.shape[0] != ACTION_DIM:
                raise ValueError(
                    f"Policy returned action of shape {action.shape}; expected ({ACTION_DIM},)"
                )

            ts = env.step(action)
            r = float(ts.reward) if ts.reward is not None else 0.0
            if r > highest_reward:
                highest_reward = r

            log(f"step {step}: reward={r} highest={highest_reward}/{env_max_reward}", log_file)
            if highest_reward >= env_max_reward:
                log(f"  Success at step={step} (reward={highest_reward}).", log_file)
                break

        if args.gui:
            try:
                import matplotlib.pyplot as plt
                plt.close()
            except Exception:
                pass

        log("", log_file)
        success = highest_reward >= env_max_reward
        log(
            f"demo finished: {last_step + 1} steps, "
            f"highest_reward={highest_reward}/{env_max_reward}, "
            f"success={success}",
            log_file,
        )

        if args.save_video and frames:
            try:
                import imageio
                mp4 = os.path.join(run_dir, "demo.mp4")
                writer = imageio.get_writer(
                    mp4, fps=args.video_fps, format="FFMPEG", codec="libx264")
                for f in frames:
                    writer.append_data(f)
                writer.close()
                log(f"saved video: {mp4}", log_file)
            except Exception as e:
                log(f"[warn] imageio write failed: {type(e).__name__}: {e}", log_file)

        log(f"log_file: {log_path}", log_file)
    finally:
        try:
            client.close()
        except Exception:
            pass
        if not log_file.closed:
            log_file.close()


if __name__ == "__main__":
    main()
